/***
Ben Bailey
types.c
***/

#include "types.h"

char *VARIABLE = "IDENTIFIER";
char *VAR = "VAR";
char *INTEGER = "INT";
char *STRING = "STRING";
char *REAL = "REAL";
char *UNKNOWN = "UNKNOWN";
char *BADNUMBER = "BAD NUMBER";

char *POUND = "POUND";
char *QUOTE = "DOUBLE QUOTE";
char *SQUOTE = "SINGLE QUOTE";
char *LESSTHAN = "LESS THAN / OPEN ANGLE BRACKET";
char *GREATERTHAN = "GREATER THAN / CLOSED ANGLE BRACKET";
char *OPAREN = "OPEN PARENTHESIS";
char *CPAREN = "CLOSED PARENTHESIS";
char *OBRACE = "OPEN BRACE";
char *CBRACE = "CLOSED BRACE";
char *OBRACKET = "OPEN BRACKET";
char *CBRACKET = "CLOSED BRACKET";
char *EXCL = "EXCLAMATION";
char *SEMI = "SEMICOLON";
char *COLON = "SEMICOLON";
char *QUESTION = "QUESTION (Comment)";

char *ASSIGN = "ASSIGN";
char *PLUS = "PLUS";
char *MINUS = "MINUS";
char *DIVIDE = "DIVIDE";
char *TIMES = "TIMES / POINTER";
char *DOT = "DOT";
char *COMMA = "COMMA";
char *MOD = "MOD";
char *ANDAND = "AND";
char *OROR = "OR";
char *EQUALSEQUALS = "EQUALS";
char *PLUSPLUS = "PLUS PLUS";
char *MINUSMINUS = "MINUS MINUS";
char *PEQUALS = "PLUS EQUALS";
char *MINUESEQUALS = "MINUES EQUALS";
char *TIMESEQUALS = "TIMES EQUALS";
char *DIVIDEEQUALS = "DIVIDE EQUALS";
char *GREATEREQUALS = "GREATEREQUALS";
char *LESSEQUALS = "LESSEQUALS";

char *IF = "IF";
char *ELSE = "ELSE";
char *FOR = "FOR";
char *WHILE = "WHILE";
char *NOT = "NOT";
// char *INCLUDE = "INCLUDE";
char *MAIN = "MAIN";
char *RETURN = "RETURN";
char *METHOD = "METHOD";
char *VOID = "VOID";
char *STRUCT = "STRUCT";
char *ENDOFINPUT = "ENDOFINPUT";


// NEW TYPES FOR PRETTY PRINTING
char *PROGRAM = "NEWTYPE";
char *INCLUDES = "NEWTYPE";
char *INCLUDE = "NEWTYPE";
char *MAINMETHOD = "NEWTYPE";
char *ARGLIST = "NEWTYPE";
char *BLOCK = "NEWTYPE";
char *STATEMENTS = "NEWTYPE";
char *STATEMENT = "NEWTYPE";
char *EXPRESSION = "NEWTYPE";
char *OPERATOR = "NEWTYPE";
char *UNARY = "NEWTYPE";
char *VARDEF = "NEWTYPE";
char *IFSTATEMENT = "NEWTYPE";
char *OPTELSE = "NEWTYPE";
char *WHILELOOP = "NEWTYPE";
char *FORLOOP = "NEWTYPE";
char *FUNCDEF = "NEWTYPE";
char *FUNCCALL = "NEWTYPE";
char *RETURNSTATEMENT = "NEWTYPE";

char *FORCHECK = "NEWTYPE";
char *FOROP = "NEWTYPE";

char *GLUE = "GLUE";
